version: '3.2'
services: 
  users-service:
    build: 
        context: .
        dockerfile: ./Dockerfile

    depends_on:
        - users-service-db
    ports:
        - 127.0.0.1:3301:3301
    volumes:  
        - ./:/opt/app
        - ./app/node_modules
        
  users-service-db:
    env_file: ./.env
    environment:
      - ACCEPT_EULA=Y
    image: mcmoe/mssqldocker
    ports:
      - 127.0.0.1:1435:1434
